services:
  cb-stacked-bot:
    image: crypto-stacked-bot:1.0
    volumes:
      - ./settings:/app/settings
    secrets:
      - cdp_api_key.json
      - webhooks.toml

      
secrets:
  cdp_api_key.json:
    file: ./config/cdp_api_key.json
  webhooks.toml:
    file: ./config/webhooks.toml
    