[BTC_USDC]
GLOBAL_PRODUCT_ID = "BTC-USDC"
GLOBAL_NEG_THRESHOLD = -4
GLOBAL_BUY_INCREMENT = "10"

[SOL_USDC]
GLOBAL_PRODUCT_ID = "SOL-USDC"
GLOBAL_NEG_THRESHOLD = -4
GLOBAL_BUY_INCREMENT = "10"

[ETH_USDC]
GLOBAL_PRODUCT_ID = "ETH-USDC"
GLOBAL_NEG_THRESHOLD = -4
GLOBAL_BUY_INCREMENT = "10"
